import lsb_release

DISTRO_INFO = lsb_release.get_distro_information()

(UPDATE_CHECKED, UPDATE_DISPLAY_NAME, UPDATE_OLD_VERSION, UPDATE_NEW_VERSION,
 UPDATE_SOURCE, UPDATE_SIZE, UPDATE_SIZE_STR, UPDATE_TYPE_PIX, UPDATE_TYPE,
 UPDATE_TOOLTIP, UPDATE_SORT_STR, UPDATE_OBJ) = range(12)
