.\"	Title : kernel-manager
.\"	Author : gm10
.\"
.\" First parameter, NAME, should be all caps
.\" other parameters are allowed: see man(7), man(1)
.TH KERNEL-MANAGER 8 "1 December 2019" MINTUPDATE
.\" Please adjust this date whenever revising the manpage.
.\"
.\" for manpage-specific macros, see man(7)
.SH NAME
kernel-manager \- Kernel Manager

.SH SYNOPSIS
\fBkernel-manager\fR

.SH DESCRIPTION
\fBkernel-manager\fR is an advanced Linux kernel manager with optional support
for Ubuntu's mainline kernel builds.

.SH NOTES
\fBkernel-manager\fR is integrated into \fBmintupdate(8)\fR and the command
will bring up the integrated version while that is running, otherwise a
stand-alone version will be launched.

.SH SEE ALSO
\fBmintupdate(8)\fR
