.\"	Title : mintupdate-launcher
.\"	Author : gm10
.\"
.\" First parameter, NAME, should be all caps
.\" other parameters are allowed: see man(7), man(1)
.TH MINTUPDATE-LAUNCHER 8 "1 December 2019" MINTUPDATE
.\" Please adjust this date whenever revising the manpage.
.\"
.\" for manpage-specific macros, see man(7)
.SH NAME
mintupdate-launcher \- Update and Kernel Manager tray launcher

.SH SYNOPSIS
\fBmintupdate-launcher\fR

.SH DESCRIPTION
\fBmintupdate-launcher\fR launches \fBmintupdate(8)\fR with the application
window hidden.
.PP
This binary exists solely for compatibility reasons for users of Linux Mint's
mintupdate who may have modified autostart files pointing to this. The default
autostart launches \fBmintupdate hide\fR instead.

.SH SEE ALSO
\fBmintupdate(8)\fR
